### ISSUE TITLE
[BOOM] Add support for BOOM

### ISSUE THREAD

**Issue by sagark** [firesim/firesim#12]
BOOM Support has been added to FireSim in the 1.2 release. However, there are still target-level bugs that need to be resolved in BOOM before it can be used fully for Linux-based software (Linux currently boots most of the way, but then hangs, which can be reproduced in both regular VCS (no sim components) and on the FPGA). See the log in the next post.

**Comment by davidbiancolin** [comment]
./simulator-boomexample-SimBlockDeviceConfig +blkdev=../../../sw/firesim-software/rootfs0.ext2 ../../../sw/firesim-software/bbl-vmlinux0
[    0.000000] OF: fdt: Ignoring memory range 0x80000000 - 0x80200000
[    0.000000] Linux version 4.15.0-rc6-31580-g9c3074b5c2cd (centos@ip-192-168-3-35.ec2.internal) (gcc version 7.2.0 (GCC)) #1 SMP Thu May 17 00:29:07 UTC 2018
[    0.000000] bootconsole [early0] enabled
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000080200000-0x000000008fffffff]
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000080200000-0x000000008fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000080200000-0x000000008fffffff]
[    0.000000] elf_hwcap is 0x1129
[    0.000000] percpu: Embedded 14 pages/cpu @        (ptrval) s24664 r0 d32680 u57344
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 64135
[    0.000000] Kernel command line: root=/dev/generic-blkdev rw
[    0.000000] Dentry cache hash table entries: 32768 (order: 6, 262144 bytes)
[    0.000000] Inode-cache hash table entries: 16384 (order: 5, 131072 bytes)
[    0.000000] Sorting __ex_table...
[    0.000000] Memory: 251516K/260096K available (2934K kernel code, 146K rwdata, 546K rodata, 140K init, 763K bss, 8580K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] Hierarchical RCU implementation.
[    0.000000]  RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=1.
[    0.000000] RCU: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[    0.000000] NR_IRQS: 0, nr_irqs: 0, preallocated irqs: 0
[    0.000000] riscv,cpu_intc,0: 64l local interrupts mapped
[    0.000000] riscv,plic0,c000000: mapped 3 interrupts to 1/2 handlers
[    0.000000] clocksource: riscv_clocksource: mask: 0xffffffffffffffff max_cycles: 0x1d854df40, max_idle_ns: 3526361616960 ns
[    0.000000] console [hvc0] enabled
[    0.000000] console [hvc0] enabled
[    0.000000] bootconsole [early0] disabled
[    0.000000] bootconsole [early0] disabled
[    0.000000] Calibrating delay loop (skipped), value calculated using timer frequency.. 2.00 BogoMIPS (lpj=4000)
[    0.000000] pid_max: default: 32768 minimum: 301
[    0.000000] Mount-cache hash table entries: 512 (order: 0, 4096 bytes)
[    0.004000] Mountpoint-cache hash table entries: 512 (order: 0, 4096 bytes)
[    0.012000] Hierarchical SRCU implementation.
[    0.016000] smp: Bringing up secondary CPUs ...
[    0.016000] smp: Brought up 1 node, 1 CPU
[    0.020000] devtmpfs: initialized
[    0.024000] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.024000] futex hash table entries: 256 (order: 2, 16384 bytes)
[    0.024000] random: get_random_u32 called from bucket_table_alloc+0x12c/0x3a8 with crng_init=0
[    0.028000] NET: Registered protocol family 16
[    0.040000] vgaarb: loaded
[    0.040000] clocksource: Switched to clocksource riscv_clocksource
[    0.048000] NET: Registered protocol family 2
[    0.052000] TCP established hash table entries: 2048 (order: 2, 16384 bytes)
[    0.052000] TCP bind hash table entries: 2048 (order: 3, 32768 bytes)
[    0.056000] TCP: Hash tables configured (established 2048 bind 2048)
[    0.056000] UDP hash table entries: 256 (order: 1, 8192 bytes)
[    0.056000] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes)
[    0.060000] NET: Registered protocol family 1
[    0.064000] workingset: timestamp_bits=62 max_order=16 bucket_order=0
[    0.068000] random: fast init done
[    0.100000] io scheduler noop registered
[    0.100000] io scheduler cfq registered (default)
[    0.100000] io scheduler mq-deadline registered
[    0.100000] io scheduler kyber registered
[    0.376000] disk [generic-blkdev] of loaded; 3800800 sectors, 1 tags, 16 max request length
[    0.396000] VFS: Mounted root (ext2 filesystem) on device 254:0.
[    0.400000] devtmpfs: mounted
[    0.400000] Freeing unused kernel memory: 140K
[    0.400000] This architecture does not have kernel memory protection.

**Comment by davidbiancolin** [comment]
^ Just putting it there to keep a record. The same thing can be reproduced on the FPGA.

**Comment by sagark** [comment]
Let's merge Jerry's fixes to boom, then firechip, then dev branch on firesim and do a release of stable single-core BOOM in simulation this weekend, before Chris' talk.
