### ISSUE TITLE
TracerV segfaults on a bare-metal workload

### ISSUE THREAD

**Issue by vargandhi** [firesim/firesim#1231]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/firesim)
- [X] Yes, I searched [prior issues](https://github.com/firesim/firesim/issues)
- [X] Yes, I searched the [documentation](https://docs.fires.im/en/stable/)

### FireSim Version and Hash

1.14.2-0-g8c5416c0 

### OS Setup

Linux ip-192-168-0-95.ec2.internal 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core

### Other Setup

I'm running firesim as a submodule of chipyard.

### Current Behavior

I’m trying to profile a sample bare-metal workload defined in bare.yaml (firemarshal/test/) using tracerV on a quad-core-rocket config. The simulation runs fine without tracerV enabled, and I see “Hello World” in the uartlog generated. However, when I enable tracerV, the simulation terminates with a segfault:

Script started on Fri 23 Sep 2022 12:01:36 AM UTC
AFI ID for Slot  0: agfi-0c1b4d7cf927b4df8^M
AFI PCI  Vendor ID: 0x1d0f, Device ID 0xf000^M
Using xdma write queue: /dev/xdma0_h2c_0^M
Using xdma read queue: /dev/xdma0_c2h_0^M
UART0 is here (stdin/stdout).^M
command line for program 0. argc=57:^M
+permissive +mm_relaxFunctionalModel_0=0 +mm_openPagePolicy_0=1 +mm_backendLatency_0=2 +mm_schedulerWindowSize_0=8 +mm_transactionQueueDepth_0=8 +mm_dramTimings_tAL_0=0 +mm_dramTimings_tCAS_0=14 +mm_dramTimings_tCMD_0=1 +mm_dramTimings_tCWD_0=10 +mm_dramTimings_tCCD_0=4 +mm_dramTimings_tFAW_0=25 +mm_dramTimings_tRAS_0=33 +mm_dramTimings_tREFI_0=7800 +mm_dramTimings_tRC_0=47 +mm_dramTimings_tRCD_0=14 +mm_dramTimings_tRFC_0=160 +mm_dramTimings_tRRD_0=8 +mm_dramTimings_tRP_0=14 +mm_dramTimings_tRTP_0=8 +mm_dramTimings_tRTRS_0=2 +mm_dramTimings_tWR_0=15 +mm_dramTimings_tWTR_0=8 +mm_rowAddr_offset_0=18 +mm_rowAddr_mask_0=65535 +mm_rankAddr_offset_0=16 +mm_rankAddr_mask_0=3 +mm_bankAddr_offset_0=13 +mm_bankAddr_mask_0=7 +mm_llc_wayBits_0=3 +mm_llc_setBits_0=12 +mm_llc_blockBits_0=7 +mm_llc_activeMSHRs_0=8 +slotid=0 +profile-interval=-1 +macaddr0=00:12:6D:00:00:02 +blkdev0=bare-mem0-dummy.rootfs +niclog0=niclog0 +blkdev-log0=blkdev-log0 +tracefile=TRACEFILE +trace-select=0 +trace-start=0 +trace-end=-1 +trace-output-format=0 +dwarf-file-name=bare-mem0-hello-dwarf +autocounter-readrate=100 +autocounter-filename-base=AUTOCOUNTERFILE +drj_dtb=bare-mem0-hello.dtb +drj_bin=bare-mem0-hello +drj_rom=bare-mem0-hello.rom +print-start=0 +print-end=-1 +linklatency0=6405 +netbw0=200 +shmemportname0=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 +permissive-off bare-mem0-hello ^M
using link latency: 6405 cycles^M
using netbw: 200^M
using netburst: 8^M
Using non-slot-id associated shmemportname:^M
opening/creating shmem region^M
/port_nts0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000_0^M
Using non-slot-id associated shmemportname:^M
opening/creating shmem region^M
/port_stn0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000_0^M
Using non-slot-id associated shmemportname:^M
opening/creating shmem region^M
/port_nts0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000_1^M
Using non-slot-id associated shmemportname:^M
opening/creating shmem region^M
/port_stn0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000_1^M
random min: 0x0, random max: 0xffffffffffffffff^M
TracerV: No trigger selected. Trigger enabled from 0 to 18446744073709551615 cycles^M
TracerV: No trigger selected. Trigger enabled from 0 to 18446744073709551615 cycles^M
TracerV: No trigger selected. Trigger enabled from 0 to 18446744073709551615 cycles^M
TracerV: No trigger selected. Trigger enabled from 0 to 18446744073709551615 cycles^M
Commencing simulation.^M
bash: line 1: 17955 Segmentation fault      sudo ./FireSim-f1 +permissive +mm_relaxFunctionalModel_0=0 +mm_openPagePolicy_0=1 +mm_backendLatency_0=2 +mm_schedulerWindowSize_0=8 +mm_transactionQueueDepth_0=8 +mm_dramTimings_tAL_0=0 +mm_dramTimings_tCAS_0=14 +mm_dramTimings_tCMD_0=1 +mm_dramTimings_tCWD_0=10 +mm_dramTimings_tCCD_0=4 +mm_dramTimings_tFAW_0=25 +mm_dramTimings_tRAS_0=33 +mm_dramTimings_tREFI_0=7800 +mm_dramTimings_tRC_0=47 +mm_dramTimings_tRCD_0=14 +mm_dramTimings_tRFC_0=160 +mm_dramTimings_tRRD_0=8 +mm_dramTimings_tRP_0=14 +mm_dramTimings_tRTP_0=8 +mm_dramTimings_tRTRS_0=2 +mm_dramTimings_tWR_0=15 +mm_dramTimings_tWTR_0=8 +mm_rowAddr_offset_0=18 +mm_rowAddr_mask_0=65535 +mm_rankAddr_offset_0=16 +mm_rankAddr_mask_0=3 +mm_bankAddr_offset_0=13 +mm_bankAddr_mask_0=7 +mm_llc_wayBits_0=3 +mm_llc_setBits_0=12 +mm_llc_blockBits_0=7 +mm_llc_activeMSHRs_0=8 +slotid=0 +profile-interval=-1 +macaddr0=00:12:6D:00:00:02 +blkdev0=bare-mem0-dummy.rootfs +niclog0=niclog0 +blkdev-log0=blkdev-log0 +tracefile=TRACEFILE +trace-select=0 +trace-start=0 +trace-end=-1 +trace-output-format=0 +dwarf-file-name=bare-mem0-hello-dwarf +autocounter-readrate=100 +autocounter-filename-base=AUTOCOUNTERFILE +drj_dtb=bare-mem0-hello.dtb +drj_bin=bare-mem0-hello +drj_rom=bare-mem0-hello.rom +print-start=0 +print-end=-1 +linklatency0=6405 +netbw0=200 +shmemportname0=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 +permissive-off +prog0=bare-mem0-hello^M

### Expected Behavior

The bare-metal workload should run and generate a uartlog with the "Hello World" output, i.e., similar to the one generated when tracerV is not enabled.

Script started on Thu 22 Sep 2022 11:19:32 PM UTC
AFI ID for Slot  0: agfi-0c1b4d7cf927b4df8^M
AFI PCI  Vendor ID: 0x1d0f, Device ID 0xf000^M
Using xdma write queue: /dev/xdma0_h2c_0^M
Using xdma read queue: /dev/xdma0_c2h_0^M
UART0 is here (stdin/stdout).^M
command line for program 0. argc=56:^M
+permissive +mm_relaxFunctionalModel_0=0 +mm_openPagePolicy_0=1 +mm_backendLatency_0=2 +mm_schedulerWindowSize_0=8 +mm_transactionQueueDepth_0=8 +mm_dramTimings_tAL_0=0 +mm_dramTimings_tCAS_0=14 +mm_dramTimings_tCMD_0=1 +mm_dramTimings_tCWD_0=10 +mm_dramTimings_tCCD_0=4 +mm_dramTimings_tFAW_0=25 +mm_dramTimings_tRAS_0=33 +mm_dramTimings_tREFI_0=7800 +mm_dramTimings_tRC_0=47 +mm_dramTimings_tRCD_0=14 +mm_dramTimings_tRFC_0=160 +mm_dramTimings_tRRD_0=8 +mm_dramTimings_tRP_0=14 +mm_dramTimings_tRTP_0=8 +mm_dramTimings_tRTRS_0=2 +mm_dramTimings_tWR_0=15 +mm_dramTimings_tWTR_0=8 +mm_rowAddr_offset_0=18 +mm_rowAddr_mask_0=65535 +mm_rankAddr_offset_0=16 +mm_rankAddr_mask_0=3 +mm_bankAddr_offset_0=13 +mm_bankAddr_mask_0=7 +mm_llc_wayBits_0=3 +mm_llc_setBits_0=12 +mm_llc_blockBits_0=7 +mm_llc_activeMSHRs_0=8 +slotid=0 +profile-interval=-1 +macaddr0=00:12:6D:00:00:02 +blkdev0=bare-mem0-dummy.rootfs +niclog0=niclog0 +blkdev-log0=blkdev-log0 +trace-select=1 +trace-start=0 +trace-end=-1 +trace-output-format=0 +dwarf-file-name=bare-mem0-hello-dwarf +autocounter-readrate=0 +autocounter-filename-base=AUTOCOUNTERFILE +drj_dtb=bare-mem0-hello.dtb +drj_bin=bare-mem0-hello +drj_rom=bare-mem0-hello.rom +print-start=0 +print-end=-1 +linklatency0=6405 +netbw0=200 +shmemportname0=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 +permissive-off bare-mem0-hello ^M
using link latency: 6405 cycles^M
using netbw: 200^M
using netburst: 8^M
Using non-slot-id associated shmemportname:^M
opening/creating shmem region^M
/port_nts0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000_0^M
Using non-slot-id associated shmemportname:^M
opening/creating shmem region^M
/port_stn0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000_0^M
Using non-slot-id associated shmemportname:^M
opening/creating shmem region^M
/port_nts0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000_1^M
Using non-slot-id associated shmemportname:^M
opening/creating shmem region^M
/port_stn0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000_1^M
TraceRV 0: Tracing disabled, since +tracefile was not provided.^M
TraceRV 1: Tracing disabled, since +tracefile was not provided.^M
TraceRV 2: Tracing disabled, since +tracefile was not provided.^M
TraceRV 3: Tracing disabled, since +tracefile was not provided.^M
random min: 0x0, random max: 0xffffffffffffffff^M
TracerV: Trigger enabled from 0 to 18446744073709551615 cycles^M
TracerV: Trigger enabled from 0 to 18446744073709551615 cycles^M
TracerV: Trigger enabled from 0 to 18446744073709551615 cycles^M
TracerV: Trigger enabled from 0 to 18446744073709551615 cycles^M
Commencing simulation.^M
Hello World^M
^M
Simulation complete.^M
*** PASSED *** after 60142951 cycles^M
^M
Emulation Performance Summary^M
------------------------------^M
Wallclock Time Elapsed: 1.1 s^M
Host Frequency: 89.999 MHz^M
Target Cycles Emulated: 60142951^M
Effective Target Frequency: 53.262 MHz^M
FMR: 1.69^M
Note: The latter three figures are based on the fastest target clock.^M

Script done on Thu 22 Sep 2022 11:19:33 PM UTC

### Other Information

My config_runtime.yaml: 

run_farm:
  base_recipe: run-farm-recipes/aws_ec2.yaml
  recipe_arg_overrides:
    # tag to apply to run farm hosts
    run_farm_tag: mainrunfarm
    # enable expanding run farm by run_farm_hosts given
    always_expand_run_farm: true
    # minutes to retry attempting to request instances
    launch_instances_timeout_minutes: 60
    # run farm host market to use (ondemand, spot)
    run_instance_market: ondemand
    # if using spot instances, determine the interrupt behavior (terminate, stop, hibernate)
    spot_interruption_behavior: terminate
    # if using spot instances, determine the max price
    spot_max_price: ondemand
    # default location of the simulation directory on the run farm host
    default_simulation_dir: /home/centos

    # run farm hosts to spawn: a mapping from a spec below (which is an EC2
    # instance type) to the number of instances of the given type that you
    # want in your runfarm.
    run_farm_hosts_to_use:
      - f1.16xlarge: 0
      - f1.4xlarge: 0
      - f1.2xlarge: 1
      - m4.16xlarge: 0
      - z1d.3xlarge: 0
      - z1d.6xlarge: 0
      - z1d.12xlarge: 0

metasimulation:
  metasimulation_enabled: false
  # vcs or verilator. use vcs-debug or verilator-debug for waveform generation
  metasimulation_host_simulator: verilator
  # plusargs passed to the simulator for all metasimulations
  metasimulation_only_plusargs: "+fesvr-step-size=128 +dramsim +max-cycles=100000000"
  # plusargs passed to the simulator ONLY FOR vcs metasimulations
  metasimulation_only_vcs_plusargs: "+vcs+initreg+0 +vcs+initmem+0"

target_config:
    # Set topology: no_net_config to run without a network simulation
    topology: example_1config
    no_net_num_nodes: 2
    link_latency: 6405
    switching_latency: 10
    net_bandwidth: 200
    profile_interval: -1

    # This references a section from config_hwdb.yaml for fpga-accelerated simulation
    # or from config_build_recipes.yaml for metasimulation
    # In homogeneous configurations, use this to set the hardware config deployed
    # for all simulators
    default_hw_config: firesim_rocket_quadcore_nic_l2_llc4mb_ddr3

    # Advanced: Specify any extra plusargs you would like to provide when
    # booting the simulator (in both FPGA-sim and metasim modes). This is
    # a string, with the contents formatted as if you were passing the plusargs
    # at command line, e.g. "+a=1 +b=2”
    plusarg_passthrough: ""

tracing:
    enable: yes

    # Trace output formats. Only enabled if "enable" is set to "yes" above
    # 0 = human readable; 1 = binary (compressed raw data); 2 = flamegraph (stack
    # unwinding -> Flame Graph)
    output_format: 0

    # Trigger selector.
    # 0 = no trigger; 1 = cycle count trigger; 2 = program counter trigger; 3 =
    # instruction trigger
    selector: 0
    start: 0
    end: -1

autocounter:
    read_rate: 100

workload:
    workload_name: bare-mem.json
    terminate_on_completion: no
    suffix_tag: null

host_debug:
    # When enabled (=yes), Zeros-out FPGA-attached DRAM before simulations
    # begin (takes 2-5 minutes).
    # In general, this is not required to produce deterministic simulations on
    # target machines running linux. Enable if you observe simulation non-determinism.
    zero_out_dram: no
    # If disable_synth_asserts: no, simulation will print assertion message and
    # terminate simulation if synthesized assertion fires.
    # If disable_synth_asserts: yes, simulation ignores assertion firing and
    # continues simulation.
    disable_synth_asserts: no

# DOCREF START: Synthesized Prints
synth_print:
    # Start and end cycles for outputting synthesized prints.
    # They are given in terms of the base clock and will be converted
    # for each clock domain.
    start: 0
    end: -1
    # When enabled (=yes), prefix print output with the target cycle at which the print was triggered
    cycle_prefix: yes
# DOCREF END: Synthesized Prints

**Comment by davidbiancolin** [comment]
Hey Varan, could you confirm this still happens using one of the pre-compiled RISC-V baremetal tests. I'd try a longer one such as mm, which you can find here:
 $RISCV/riscv64-unknown-elf/share/riscv-tests/benchmarks/mm.riscv

**Comment by vargandhi** [comment]
Hi David,

Yes, I can confirm that tracerV segfaults on mm.riscv. Whereas mm.riscv works fine when I disable tracing from my config_runtime.yaml

Also, I’m running these workloads on a quad-core medium Boom config. Not sure if that would make a difference though...

Here’s the uartlog for the two runs —

TracerV enabled 

Script started on Tue 27 Sep 2022 09:01:10 PM UTC
AFI ID for Slot  0: agfi-0568d760705e5f378^M
AFI PCI  Vendor ID: 0x1d0f, Device ID 0xf000^M
Using xdma write queue: /dev/xdma0_h2c_0^M
Using xdma read queue: /dev/xdma0_c2h_0^M
UART0 is here (stdin/stdout).^M
command line for program 0. argc=57:^M
+permissive +mm_relaxFunctionalModel_0=0 +mm_openPagePolicy_0=1 +mm_backendLatency_0=2 +mm_schedulerWindowSize_0=8 +mm_transactionQueueDepth_0=8 +mm_dramTimings_tAL_0=0 +mm_dramTimings_tCAS_0=14 +mm_dramTimings_tCMD_0=1 +mm_dramTimings_tCWD_0=10 +mm_dramTimings_tCCD_0=4 +mm_dramTimings_tFAW_0=25 +mm_dramTimings_tRAS_0=33 +mm_dramTimings_tREFI_0=7800 +mm_dramTimings_tRC_0=47 +mm_dramTimings_tRCD_0=14 +mm_dramTimings_tRFC_0=160 +mm_dramTimings_tRRD_0=8 +mm_dramTimings_tRP_0=14 +mm_dramTimings_tRTP_0=8 +mm_dramTimings_tRTRS_0=2 +mm_dramTimings_tWR_0=15 +mm_dramTimings_tWTR_0=8 +mm_rowAddr_offset_0=18 +mm_rowAddr_mask_0=65535 +mm_rankAddr_offset_0=16 +mm_rankAddr_mask_0=3 +mm_bankAddr_offset_0=13 +mm_bankAddr_mask_0=7 +mm_llc_wayBits_0=3 +mm_llc_setBits_0=12 +mm_llc_blockBits_0=7 +mm_llc_activeMSHRs_0=8 +slotid=0 +profile-interval=-1 +macaddr0=00:12:6D:00:00:02 +blkdev0=riscv-mm0-dummy.rootfs +niclog0=niclog0 +blkdev-log0=blkdev-log0 +tracefile=TRACEFILE +trace-select=0 +trace-start=0 +trace-end=-1 +trace-output-format=0 +dwarf-file-name=riscv-mm0-mm.riscv-dwarf +autocounter-readrate=0 +autocounter-filename-base=AUTOCOUNTERFILE +drj_dtb=riscv-mm0-mm.riscv.dtb +drj_bin=riscv-mm0-mm.riscv +drj_rom=riscv-mm0-mm.riscv.rom +print-start=0 +print-end=-1 +linklatency0=6405 +netbw0=200 +shmemportname0=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 +permissive-off riscv-mm0-mm.riscv ^M
using link latency: 6405 cycles^M
using netbw: 200^M
using netburst: 8^M
Using non-slot-id associated shmemportname:^M
opening/creating shmem region^M
/port_nts0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000_0^M
Using non-slot-id associated shmemportname:^M
opening/creating shmem region^M
/port_stn0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000_0^M
Using non-slot-id associated shmemportname:^M
opening/creating shmem region^M
/port_nts0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000_1^M
Using non-slot-id associated shmemportname:^M
opening/creating shmem region^M
/port_stn0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000_1^M
random min: 0x0, random max: 0xffffffffffffffff^M
TracerV: No trigger selected. Trigger enabled from 0 to 18446744073709551615 cycles^M
TracerV: No trigger selected. Trigger enabled from 0 to 18446744073709551615 cycles^M
TracerV: No trigger selected. Trigger enabled from 0 to 18446744073709551615 cycles^M
TracerV: No trigger selected. Trigger enabled from 0 to 18446744073709551615 cycles^M
Commencing simulation.^M
bash: line 1: 29297 Segmentation fault      sudo ./FireSim-f1 +permissive +mm_relaxFunctionalModel_0=0 +mm_openPagePolicy_0=1 +mm_backendLatency_0=2 +mm_schedulerWindowSize_0=8 +mm_transactionQueueDepth_0=8 +mm_dramTimings_tAL_0=0 +mm_dramTimings_tCAS_0=14 +mm_dramTimings_tCMD_0=1 +mm_dramTimings_tCWD_0=10 +mm_dramTimings_tCCD_0=4 +mm_dramTimings_tFAW_0=25 +mm_dramTimings_tRAS_0=33 +mm_dramTimings_tREFI_0=7800 +mm_dramTimings_tRC_0=47 +mm_dramTimings_tRCD_0=14 +mm_dramTimings_tRFC_0=160 +mm_dramTimings_tRRD_0=8 +mm_dramTimings_tRP_0=14 +mm_dramTimings_tRTP_0=8 +mm_dramTimings_tRTRS_0=2 +mm_dramTimings_tWR_0=15 +mm_dramTimings_tWTR_0=8 +mm_rowAddr_offset_0=18 +mm_rowAddr_mask_0=65535 +mm_rankAddr_offset_0=16 +mm_rankAddr_mask_0=3 +mm_bankAddr_offset_0=13 +mm_bankAddr_mask_0=7 +mm_llc_wayBits_0=3 +mm_llc_setBits_0=12 +mm_llc_blockBits_0=7 +mm_llc_activeMSHRs_0=8 +slotid=0 +profile-interval=-1 +macaddr0=00:12:6D:00:00:02 +blkdev0=riscv-mm0-dummy.rootfs +niclog0=niclog0 +blkdev-log0=blkdev-log0 +tracefile=TRACEFILE +trace-select=0 +trace-start=0 +trace-end=-1 +trace-output-format=0 +dwarf-file-name=riscv-mm0-mm.riscv-dwarf +autocounter-readrate=0 +autocounter-filename-base=AUTOCOUNTERFILE +drj_dtb=riscv-mm0-mm.riscv.dtb +drj_bin=riscv-mm0-mm.riscv +drj_rom=riscv-mm0-mm.riscv.rom +print-start=0 +print-end=-1 +linklatency0=6405 +netbw0=200 +shmemportname0=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 +permissive-off +prog0=riscv-mm0-mm.riscv^M

Script done on Tue 27 Sep 2022 09:01:10 PM UTC


————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————


TracerV NOT enabled 

Script started on Tue 27 Sep 2022 08:54:00 PM UTC
AFI ID for Slot  0: agfi-0568d760705e5f378^M
AFI PCI  Vendor ID: 0x1d0f, Device ID 0xf000^M
Using xdma write queue: /dev/xdma0_h2c_0^M
Using xdma read queue: /dev/xdma0_c2h_0^M
UART0 is here (stdin/stdout).^M
command line for program 0. argc=56:^M
+permissive +mm_relaxFunctionalModel_0=0 +mm_openPagePolicy_0=1 +mm_backendLatency_0=2 +mm_schedulerWindowSize_0=8 +mm_transactionQueueDepth_0=8 +mm_dramTimings_tAL_0=0 +mm_dramTimings_tCAS_0=14 +mm_dramTimings_tCMD_0=1 +mm_dramTimings_tCWD_0=10 +mm_dramTimings_tCCD_0=4 +mm_dramTimings_tFAW_0=25 +mm_dramTimings_tRAS_0=33 +mm_dramTimings_tREFI_0=7800 +mm_dramTimings_tRC_0=47 +mm_dramTimings_tRCD_0=14 +mm_dramTimings_tRFC_0=160 +mm_dramTimings_tRRD_0=8 +mm_dramTimings_tRP_0=14 +mm_dramTimings_tRTP_0=8 +mm_dramTimings_tRTRS_0=2 +mm_dramTimings_tWR_0=15 +mm_dramTimings_tWTR_0=8 +mm_rowAddr_offset_0=18 +mm_rowAddr_mask_0=65535 +mm_rankAddr_offset_0=16 +mm_rankAddr_mask_0=3 +mm_bankAddr_offset_0=13 +mm_bankAddr_mask_0=7 +mm_llc_wayBits_0=3 +mm_llc_setBits_0=12 +mm_llc_blockBits_0=7 +mm_llc_activeMSHRs_0=8 +slotid=0 +profile-interval=-1 +macaddr0=00:12:6D:00:00:02 +blkdev0=riscv-mm0-dummy.rootfs +niclog0=niclog0 +blkdev-log0=blkdev-log0 +trace-select=0 +trace-start=0 +trace-end=-1 +trace-output-format=0 +dwarf-file-name=riscv-mm0-mm.riscv-dwarf +autocounter-readrate=0 +autocounter-filename-base=AUTOCOUNTERFILE +drj_dtb=riscv-mm0-mm.riscv.dtb +drj_bin=riscv-mm0-mm.riscv +drj_rom=riscv-mm0-mm.riscv.rom +print-start=0 +print-end=-1 +linklatency0=6405 +netbw0=200 +shmemportname0=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 +permissive-off riscv-mm0-mm.riscv ^M
using link latency: 6405 cycles^M
using netbw: 200^M
using netburst: 8^M
Using non-slot-id associated shmemportname:^M
opening/creating shmem region^M
/port_nts0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000_0^M
Using non-slot-id associated shmemportname:^M
opening/creating shmem region^M
/port_stn0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000_0^M
Using non-slot-id associated shmemportname:^M
opening/creating shmem region^M
/port_nts0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000_1^M
Using non-slot-id associated shmemportname:^M
opening/creating shmem region^M
/port_stn0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000_1^M
TraceRV 0: Tracing disabled, since +tracefile was not provided.^M
TraceRV 1: Tracing disabled, since +tracefile was not provided.^M
TraceRV 2: Tracing disabled, since +tracefile was not provided.^M
TraceRV 3: Tracing disabled, since +tracefile was not provided.^M
random min: 0x0, random max: 0xffffffffffffffff^M
TracerV: No trigger selected. Trigger enabled from 0 to 18446744073709551615 cycles^M
TracerV: No trigger selected. Trigger enabled from 0 to 18446744073709551615 cycles^M
TracerV: No trigger selected. Trigger enabled from 0 to 18446744073709551615 cycles^M
TracerV: No trigger selected. Trigger enabled from 0 to 18446744073709551615 cycles^M
Commencing simulation.^M
C0: reg block 4x5x6, cache block 24x25x24^M
C0: 24688 instructions^M
C0: 16568 cycles^M
C0: 28800 flops^M
C0: 1738 Mflops @ 1 GHz^M
^M
Simulation complete.^M
*** PASSED *** after 194462207 cycles^M
^M
Emulation Performance Summary^M
------------------------------^M
Wallclock Time Elapsed: 4.7 s^M
Host Frequency: 64.999 MHz^M
Target Cycles Emulated: 194462207^M
Effective Target Frequency: 41.136 MHz^M
FMR: 1.58^M
Note: The latter three figures are based on the fastest target clock.^M

Script done on Tue 27 Sep 2022 08:54:05 PM UTC
~

**Comment by vargandhi** [comment]
Hi David,

I was wondering if you got a chance to look into it. Is there anything I could try on my side to debug this issue?

Best,
Varun

**Comment by davidbiancolin** [comment]
@vargandhi can you try cherry-picking the change in #1249? Let me know if it helps.

**Comment by vargandhi** [comment]
@davidbiancolin -- I'm using firesim as a library in chipyard and am not able to finish the manager instance setup after modifying the firesim source code. I keep getting the following error:
Traceback (most recent call last):
  File "/home/centos/chipyard/sims/firesim/deploy/firesim", line 28, in <module>
    from runtools.runtime_config import RuntimeConfig
  File "/home/centos/chipyard/sims/firesim/deploy/runtools/runtime_config.py", line 17, in <module>
    from runtools.firesim_topology_with_passes import FireSimTopologyWithPasses
  File "/home/centos/chipyard/sims/firesim/deploy/runtools/firesim_topology_with_passes.py", line 11, in <module>
    from colorama import Fore, Style # type: ignore
ModuleNotFoundError: No module named 'colorama'

Although, at this point, I'm not sure if this is an issue on the firesim side or chipyard. I'm building the chipyard repo with branch 1.7.1 but not sure if it's still the most recent stable version. The stable version of the chipyard documentation is missing this info.

**Comment by vargandhi** [comment]
@davidbiancolin -- I successfully ran tracerV after making the suggested change. Thanks!
