### ISSUE TITLE
mutilate-loadgen-riscv-release

### ISSUE THREAD

**Issue by sumiranb** [firesim/firesim#1473]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/firesim)
- [X] Yes, I searched [prior issues](https://github.com/firesim/firesim/issues)
- [X] Yes, I searched the [documentation](https://docs.fires.im/en/stable/)

### FireSim Version and Hash

git rev-parse FETCH_HEAD:
0b1b619e6ce466b77c5f0de9a786ebd8a32764ee

version: 1.8.1 (cloned from chipyard directly , stable version)

### OS Setup

OpennSuseLinux

### Other Setup

The setup is exactly followed here : https://chipyard.readthedocs.io/en/stable/Chipyard-Basics/Initial-Repo-Setup.html

### Current Behavior

According to the instructions, we need to run the build.sh from this directory:
/chipyard/sims/firesim/deploy/workloads/memcached-thread-imbalance/mutilate-loadgen-riscv-release

But on running that we get the following error:
![image](https://user-images.githubusercontent.com/89999554/226118446-60c40c54-63cc-4a73-90ce-be2d017c24fe.png)

I believe the error is due to libevent (a prerequiste) not being built properly. However, we are running it inside the firesim repository, which gives acces to all prerequiste packages. Or are we missing something to enabel those ones?

### Expected Behavior

No errors and clean compilation!

**Comment by abejgonzalez** [comment]
This should be fixed in the upcoming FireSim release (happening EOD today).
