### ISSUE TITLE
[U250] OpenSBI hangs 

### ISSUE THREAD

**Issue by ncppd** [firesim/firesim#1475]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/firesim)
- [X] Yes, I searched [prior issues](https://github.com/firesim/firesim/issues)
- [X] Yes, I searched the [documentation](https://docs.fires.im/en/stable/)

### FireSim Version and Hash

1.15.1-313-gf3bf5072

### OS Setup

Linux quest 5.4.0-144-generic #161-Ubuntu SMP Fri Feb 3 14:49:04 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

### Current Behavior

After latest commit [f3bf507](https://github.com/firesim/firesim/commit/f3bf5072bbf94e86f0e9b5618b27a529b01fe4e7) OpenSBI hangs before entering Linux on the U250 board. I tried to run qemu with the provided `br-base-bin` and it works fine, so it seems that some configuration does not work correctly on the FPGA. Do you have any pointers for this? 

### Expected Behavior

Linux should boot.

**Comment by abejgonzalez** [comment]
This is going to be fixed by EOD today (we are finishing a release of both Chipyard and FireSim so both might be unstable for a few hours)
