### ISSUE TITLE
Broken link to AWS CLI credentials doc

### ISSUE THREAD

**Issue by timsnyder-siv** [firesim/firesim#1574]
https://github.com/firesim/firesim/blob/df095fb4b8c93a0a922e4cd389ee90ed91e5fc65/docs/Initial-Setup/Setting-up-your-Manager-Instance.rst?plain=1#L156

The link we're pointing to in the above referenced docs redirects to the toplevel at https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html as of opening this ticket.  We should probably fix or remove that link.

**Comment by sagark** [comment]
Thanks for the heads up, this is fixed in #1585
