### ISSUE TITLE
Error in ./machine-launch-script.sh

### ISSUE THREAD

**Issue by zhejianguk** [firesim/firesim#1576]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/firesim)
- [X] Yes, I searched [prior issues](https://github.com/firesim/firesim/issues)
- [X] Yes, I searched the [documentation](https://docs.fires.im/en/stable/)

### FireSim Version and Hash

1.15.2-0-g186d93f

### OS Setup

```
<!-- copy/paste the output of `uname -a; lsb_release -a` below -->
```
Linux ip-192-168-2-94.eu-west-1.compute.internal 3.10.0-1160.81.1.el7.x86_64 #1 SMP Fri Dec 16 17:29:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.9.2009 (Core)
Release:	7.9.2009
Codename:	Core

### Current Behavior

I am running FireSim 1.15.2 on  FPGA Developer AMI - 1.12.2-40257ab5-6688-4c95-97d1-e251a40fd1fc (I used to run FireSim 1.14.2 successfully on April)

However, I have following errors while running  ./machine-launch-script.sh

Solving environment: ...working... failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1118, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.10/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/opt/conda/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 91, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.10/site-packages/conda/notices/core.py", line 109, in wrapper
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.10/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/opt/conda/lib/python3.10/site-packages/conda/cli/install.py", line 264, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/opt/conda/lib/python3.10/site-packages/conda/core/solve.py", line 136, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/opt/conda/lib/python3.10/site-packages/conda/core/solve.py", line 179, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 188, in solve_final_state
        out_state = self._solving_loop(in_state, out_state, index)
      File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 257, in _solving_loop
        self._export_solved_records(in_state, out_state, index)
      File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 653, in _export_solved_records
        raise KeyError(
    KeyError: "missing key 'https://conda.anaconda.org/conda-forge' in channel map: dict_keys(['https://conda.anaconda.org/conda-forge/linux-64', 'https://conda.anaconda.org/conda-forge/noarch', 'https://conda.anaconda.org/ucb-bar/linux-64', 'https://conda.anaconda.org/ucb-bar/noarch'])"

`$ /opt/conda/bin/conda create -n firesim -c conda-forge -y bash-completion ca-certificates mosh vim git screen argcomplete==1.12.3 conda-lock>=1 expect python boto3==1.20.21 pytz mypy-boto3-s3==1.21.0`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/opt/conda
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/sbin:/bin:/usr/sbin:/usr/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
             SUDO_COMMAND=/opt/conda/bin/conda create -n firesim -c conda-forge -y bash-
                          completion ca-certificates mosh vim git screen argcomplete==1.12.3
                          conda-lock>=1 expect python boto3==1.20.21 pytz mypy-boto3-s3==1.21.0
                 SUDO_GID=1000
                 SUDO_UID=1000
                SUDO_USER=centos

     active environment : None
       user config file : /root/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 22.11.1
    conda-build version : 3.25.0
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/ucb-bar/linux-64
                          https://conda.anaconda.org/ucb-bar/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/22.11.1 requests/2.28.2 CPython/3.10.9 Linux/3.10.0-1160.81.1.el7.x86_64 centos/7.9.2009 glibc/2.17 solver/libmamba conda-libmamba-solver/22.8.1 libmambapy/1.4.5
                UID:GID : 0:0
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

### Expected Behavior

The Firesim should run

**Comment by sagark** [comment]
Replied to this on the mailing list: https://groups.google.com/g/firesim/c/WFpDXJURG7k
