### ISSUE TITLE
FPGA Developer AMI - 1.12.1-40257ab5-6688-4c95-97d1-e251a40fd1fc is gone from AWS and My firesim doesn't work now.

### ISSUE THREAD

**Issue by hwirys** [firesim/firesim#1589]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/firesim)
- [X] Yes, I searched [prior issues](https://github.com/firesim/firesim/issues)
- [X] Yes, I searched the [documentation](https://docs.fires.im/en/stable/)

### FireSim Version and Hash

1.16.0-0-gdf095fb4b

### OS Setup

```
<!-- copy/paste the output of `uname -a; lsb_release -a` below -->
```
Linux ip-192-168-1-28.ec2.internal 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core

### Other Setup

I already followed up Documentation & finished whole Documentation setting. 

### Current Behavior

![image](https://github.com/firesim/firesim/assets/121537293/15b6f099-8101-4e55-a675-4905467d3700)
I got these errors when i get "firesim launchrunfarm/infrasetup/buildbitstream"

### Expected Behavior

Those works work well before FPGA Developer AMI - 1.12.1-40257ab5-6688-4c95-97d1-e251a40fd1fc is gone from AWS.

### Other Information

Those errors occured after FPGA Developer AMI - 1.12.1-40257ab5-6688-4c95-97d1-e251a40fd1fc is gone from AWS.
I think firesim need to update.

**Comment by sagark** [comment]
You should be able to fix this in your local copy by changing ``1.12.1`` to ``1.12.2`` in the string ``FPGA Developer AMI - 1.12.1-40257ab5-6688-4c95-97d1-e251a40fd1fc`` in ``deploy/awstools/awstools.py``.

Unfortunately, this AMI removal seems to keep happening without warning, so in the upcoming 1.17.0 release that will be released in a few hours, the manager will now automatically try increasing the patch version (Z in X.Y.Z) if the baked-in AMI version is not found. So hopefully this issue should not happen again.

Please re-open this issue if this does not fix your problem.
