### ISSUE TITLE
conda needs to be updated to use newer libmamba?

### ISSUE THREAD

**Issue by caizixian** [firesim/firesim#1591]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/firesim)
- [X] Yes, I searched [prior issues](https://github.com/firesim/firesim/issues)
- [X] Yes, I searched the [documentation](https://docs.fires.im/en/stable/)

### FireSim Version and Hash

I'm running the `main` (352de69b51a781378b70ffbec86147f4e62ee94c) as of writing.

### OS Setup

```
Linux alveo 5.15.0-76-generic #83~20.04.1-Ubuntu SMP Wed Jun 21 20:23:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

### Current Behavior

I'm following the getting started guide on readthedocs using the `main` version, and `./scripts/machine-launch-script.sh` fails at `conda create firesim` due to https://github.com/conda/conda-libmamba-solver/issues/145

### Expected Behavior

The installation script works.

### Other Information

This could be related to https://groups.google.com/g/firesim/c/WFpDXJURG7k and #1576. However, using the latest setup script from `main` still doesn't solve the issue for me

My current solution is to update conda itself to 23.5.0, which will then recursively update the libmamba 23.5.0, which resolves the issue for me.
```
conda config --system --set solver classic
conda update -n base -c conda-forge conda
conda config --system --set solver libmamba
```

I then rerun the `./scripts/machine-launch-script.sh` script and the `firesim` environment is created fine.

**Comment by sagark** [comment]
Thanks for the heads up @caizixian, we've fixed this in the 1.17.0 release that's coming out in a few hours.

Since there have been a few issues like this that have arisen due to pinning the installed conda version, we've updated machine launch script to always grab the latest version going forward. Hopefully that will provide better longevity.
