### ISSUE TITLE
Documentation Typo Maybe? Section 5.4.4 config_hwdb.ini

### ISSUE THREAD

**Issue by muhammadali201** [firesim/firesim#178]
The documentation section 5.4.4 sates:

> 5.4.4 config_hwdb.ini
> 
> Here is a sample of this configuration file:

 

The sample shown seems to be of of 

> `config_build_recipes.ini `

and doesn't seem to be of `config_hwdb.ini`.

Am I missing something or Did I misinterpret the documentation?

Looking in `Advanced-Usage/Manager/Manager-Configuration-Files.rst` file, I see this

![image](https://user-images.githubusercontent.com/7112875/48916778-7ed98800-eea5-11e8-9408-8a440ecbdb2e.png)

**Comment by sagark** [comment]
Thanks for pointing this out, it is indeed a mistake. I've opened a PR to fix it.
