### ISSUE TITLE
Try 64GB DRAM attached to a non-supernode config

### ISSUE THREAD

**Issue by sagark** [firesim/firesim#184]
Now that we have flexible supernode

**Comment by davidbiancolin** [comment]
I think @cookiestuf has tried this? It's a prereq for running fully fledged GAP.

**Comment by cookiestuf** [comment]
Actually, I’ve only tried 32GB DRAM (and the job errored out). I believe
48GB DRAM is enough for running GAP from running on qemu. I can give the
64gb DRAM a try though.

**Comment by davidbiancolin** [comment]
This works.
