### ISSUE TITLE
Update FireSimBoomConfig to use DefaultBoomConfig

### ISSUE THREAD

**Issue by davidbiancolin** [firesim/firesim#224]
The main problem -- that the DefaultConfig wants a 128 bit system bus -- has been resolved, and we can at least generate RTL the memory model will support.

**Comment by jerryz123** [comment]
DefaultConfig might not be able to boot linux yet.

**Comment by davidbiancolin** [comment]
:(

**Comment by jerryz123** [comment]
DefaultConfig fails to route. Did it ever work before?

MediumConfig works though, but that still uses a 64b system bus.

**Comment by davidbiancolin** [comment]
Fails to route? There are more than enough resources to host it. Does it not meet timing?
