### ISSUE TITLE
MemModel/LOADMEM address calculation issue

### ISSUE THREAD

**Issue by zhemao** [firesim/firesim#238]
When using multiple target DRAM channels, the address mapping from target to host goes wrong, and LOADMEM ends up loading to the wrong portion of host memory. Will try to find a simpler case to reproduce the bug when I have time.

**Comment by davidbiancolin** [comment]
I'm assuming you are striping along cache lines.

**Comment by zhemao** [comment]
No, I have one memory channel for the regular memory, and one for the memory for the DRAM cache. They are in separate address spaces.

**Comment by davidbiancolin** [comment]
So which region do you want to load into, and what is the target-memory map of your system.

**Comment by davidbiancolin** [comment]
We've concluded this occurs due to improperly handling heterogeneous mixes of memory models.
