### ISSUE TITLE
Memory Bug in serial_t/firesim_fesvr_t

### ISSUE THREAD

**Issue by zhemao** [firesim/firesim#249]
https://github.com/firesim/firesim/blob/dev/sim/src/main/cc/endpoints/serial.cc#L62

When creating the fesvr object, you pass in a newly constructed vector. But since the firesim_fesvr_t constructor uses a reference and the vector goes out of scope once the serial_t constructor exits, the reference will be invalid. The type of the "args" argument in firesim_fesvr_t needs to be changed so that it isn't a reference.

**Comment by davidbiancolin** [comment]
@zhemao is this resolved?

**Comment by zhemao** [comment]
Yeah, I fixed it a while back.
