### ISSUE TITLE
error in 'firesim buildafi' 

### ISSUE THREAD

**Issue by yswntht** [firesim/firesim#298]
Hi all,

I am trying to build a Firesim FPGAImage. I see 'AttributeError: Raw' and build fails.

Here is the log. 
Am I missing something??
[2019-06-14--10-45-51-buildafi-L1PJN949JM8TYEH4.log](https://github.com/firesim/firesim/files/3290440/2019-06-14--10-45-51-buildafi-L1PJN949JM8TYEH4.log)

Thanks!

**Comment by bkorpan** [comment]
I've had the same problem, it seems like the setup procedure for FireSim master is currently broken. For now, I'd recommend trying the dev branch and following the dev setup instructions: https://docs.fires.im/en/dev/Initial-Setup/index.html. The main difference is that you need to use the new FireSim AMI, which already includes the machine launch script.

**Comment by davidbiancolin** [comment]
I'm looking into this now. I'd be careful about using dev, as we're not quite ready to roll out the FireSim AMI.

**Comment by yswntht** [comment]
Yes! Also, how about using dev branch with FPGA AMI - would that work fine?

Thanks!

**Comment by davidbiancolin** [comment]
Can you run `sudo pip2 install fabric` on your manager instance. That should resolve your problem.

**Comment by yswntht** [comment]
well, I see it already present in the [flow](https://docs.fires.im/en/latest/Initial-Setup/Setting-up-your-Manager-Instance.html)

**Comment by davidbiancolin** [comment]
That's just a quick and dirty way to get pip to fix the dependency on the cryptography package. If you want to be more precise you can try: `sudo pip2 install cryptography==2.5.0`

**Comment by yswntht** [comment]
Thanks! issue resolved with your fix!
