### ISSUE TITLE
Writing to mhpmevent results in illegal instruction exception in QEMU

### ISSUE THREAD

**Issue by farzadfch** [firesim/firesim#316]
Writing to mhpmevent register in riscv-pk results in throwing an unhandled illegal instruction exception when running on QEMU and exits the simulation.
The reason is the version of QEMU which FireSim is pointing to does not handle writing to the aforementioned registers.
Upgrading to QEMU 4.0.0 fixes this issue.

**Comment by sagark** [comment]
this is fixed now
