### ISSUE TITLE
Manager ignores it when AGFI create is failed

### ISSUE THREAD

**Issue by farzadfch** [firesim/firesim#327]
In the build process, manager assumes that AGFI is created successfully even if `describe-fpga-images` says it's failed. This is discussed on the forum [here](https://groups.google.com/d/msg/firesim/CaquJ3Y9PnY/0kwzvqtiCwAJ).

**Comment by davidbiancolin** [comment]
Based on the google groups chat, the root cause seems to be a duplicate of #293. In any case, the manager should still handle these failure cases better.
