### ISSUE TITLE
Verilator install needed in `machine-launch-script.sh`?

### ISSUE THREAD

**Issue by abejgonzalez** [firesim/firesim#393]
Verilator is already cloned when you run `make` inside of Chipyard `sims/verilator`. It also uses a more recent version of Verilator `4.016`. Is this still necessary?

https://github.com/firesim/firesim/blob/7f36976cde51309834851ff4f246a2fe007ce324/scripts/machine-launch-script.sh#L37-L41

**Comment by sagark** [comment]
@abejgonzalez this is no longer relevant, right?
