### ISSUE TITLE
[RFC] Better names for software RTL simulation abstraction levels. 

### ISSUE THREAD

**Issue by davidbiancolin** [firesim/firesim#396]
Since MIDAS is gradually being renamed Golden Gate, and since @alonamid makes hay of FPGA-level simulation in every talk he gives, now's probably a good time to reconsider the names for these things. 

Target-level seems uncontroversial and should remain the same.  

My suggestions for the two simulator-levels (as categorized by Alon's talks):
`MIDAS-level ->  abstract-host level`
`FPGA-level   -> concrete-host level`

Suggestions?

**Comment by alonamid** [comment]
How about emulated-host level and full-host level?

**Comment by davidbiancolin** [comment]
Detailed-host, Abstract-host SoS -> Simulator of Simulator

**Comment by davidbiancolin** [comment]
Renamed to metasimulation.
