### ISSUE TITLE
TracerV Debug simulation hangs

### ISSUE THREAD

**Issue by sanjeev-murthy** [firesim/firesim#402]
I followed the all the steps mentioned in the Firesim documentation [http://docs.fires.im/en/1.6.0/Advanced-Usage/Debugging/TracerV.html](http://docs.fires.im/en/1.6.0/Advanced-Usage/Debugging/TracerV.html) However the simulation seems to hang when I run firesim runworkload. Kindly advise what may be wrong.

**Comment by sagark** [comment]
I believe this was resolved on the mailing list, so I'm closing it. Please let us know if it was not.
