### ISSUE TITLE
question about f1

### ISSUE THREAD

**Issue by CristinaZN** [firesim/firesim#414]
hi,
how can i copy the files in the linux system( which i screen fsim0 to)  to the manager instance
please help~~

**Comment by sagark** [comment]
The firesim manager can do this automatically, look at this page:
http://docs.fires.im/en/latest/Advanced-Usage/Workloads/Defining-Custom-Workloads.html#non-uniform-workload-json-explicit-job-per-simulated-node

See the "common_outputs" and "outputs" fields in the workload json

**Comment by CristinaZN** [comment]
many thanks~
