### ISSUE TITLE
Show `replace_rtl` output

### ISSUE THREAD

**Issue by abejgonzalez** [firesim/firesim#440]
When running replace RTL it would be nice to have the Chisel/FIRRTL output go to `stdout`. Therefore, if there is an error you can immediately see it from the terminal. This would more closely match how FireSim puts the synthesis output to both `stdout` and the log file.

**Comment by davidbiancolin** [comment]
It is captured in the log, but i think this is a good idea.

**Comment by abejgonzalez** [comment]
> It is captured in the log, but i think this is a good idea.

Sorry, I should have been clearer. It would be nice to have it go to both `stdout` and to the log file.
