### ISSUE TITLE
Don't use a global gitconfig setting to speed up recursive submodule init

### ISSUE THREAD

**Issue by davidbiancolin** [firesim/firesim#46]
For two reasons: 
- It pollutes a user's gitconfig
- It can collide with simultaneous invocations of build-setup.sh

**Comment by timsnyder-siv** [comment]
Is this still a thing?  I see usages of `git config --global` in the history but v1.8.0 doesn't seem to have any.

**Comment by davidbiancolin** [comment]
Ah, i removed them when i did the Chipyard port. Thanks!
