### ISSUE TITLE
[RFC] Factor out Trigger module from TracerV and re-use in printf synthesis, assertions, autocounter

### ISSUE THREAD

**Issue by sagark** [firesim/firesim#497]
Rather than having a single trigger mechanism within TracerV that is wired up everywhere else.

**Comment by davidbiancolin** [comment]
One thing that's not clear to me is: 
1) How many triggers should these different bridges disambiguate between? 
- Initially we could just provide one and wide-or all of the desired predicates.
- We almost definitely need to do this with some triggers -> when we duplicate TracerV bridges n-ways for n-cores, a triggered instruction or PC could appear on any of the cores. 

2) What sorts of time-resolution should these triggers provide? 
- Is it alright for some models and/or bridges to be further advanced in target time when they see the trigger? How far? 

One way we could implement this is by catching the trigger condition with a trigger bridge, and then punting to software to have the bridge drivers update bridge-module state based on the fired condition. The FPGA shell provides FPGA-driven interrupts we're currently not using which would be good for this.
