### ISSUE TITLE
Updates to machine launch script

### ISSUE THREAD

**Issue by sagark** [firesim/firesim#536]
See: https://github.com/firesim/firesim/pull/534/files/5eb5cca0472ef5848e6f0584b76647bb954e816e#diff-59c7aba9da827b75f0e1ad6de5d3aa14R22

These need to be tested on the actual FPGA dev AMI

**Comment by davidbiancolin** [comment]
@sagark The link above appears to be broken.

**Comment by sagark** [comment]
These: https://github.com/firesim/firesim/pull/534/files#diff-59c7aba9da827b75f0e1ad6de5d3aa14R22

**Comment by davidbiancolin** [comment]
Resolved in #572.
