### ISSUE TITLE
Decouple TracerV-enable and Trigger-enable

### ISSUE THREAD

**Issue by alonamid** [firesim/firesim#600]
In the current FireSim version, in order to use any bridge that may depend on a trigger, the TracerV bridge driver needs to be enabled.
I previous versions of FireSim, the trigger could be used in any AGFI that had the TracerV widget synthesized (all of them, by default), without having the trace written out to disk.

As a result, in order to use Autocounter in the current version of FireSim, the user must also output a tracefile (which really slows down simulation, because of writing the file to disk).

The rational behind the change was that TracerV was hurting FMR when it was not being used, since it was still offloading token to the host despite them not being written to disk.
The potential solution is to separate trigger-enable and tracer-enable

**Comment by davidbiancolin** [comment]
This is partially resolved in #611.

**Comment by davidbiancolin** [comment]
Update docs for 1.11
