### ISSUE TITLE
F1Shim still appears as top level module in waveform

### ISSUE THREAD

**Issue by t14916** [firesim/firesim#618]
@davidbiancolin 
Current firesim version is still simulating F1Shim as a top level module in addition to emul/FPGATop.

![f1shim](https://user-images.githubusercontent.com/16907800/89235758-d443c300-d5bc-11ea-93b1-2801c9e58a02.jpg)

**Comment by timsnyder-siv** [comment]
I noticed this again last week and it would be nice to fix.  Confuses me every time I look at waves.

**Comment by timsnyder-siv** [comment]
@t14916 were you using VCS to generate the screenshot you attached?  I'm about to post a PR that fixes VCS but doesn't do anything if this issue is also in Verilator.

**Comment by t14916** [comment]
I usually use Verilator, but the problem appears in both IIRC.
