### ISSUE TITLE
About the use of firesim

### ISSUE THREAD

**Issue by hz1490919302** [firesim/firesim#621]
Does firesim have to be used on AWS EC2 F1? I just registered for an AWS account, but I can’t get EC2 F1. EC2 F1 requires me to pay more than $1,000 a month, which is so expensive. How do you use firesim

**Comment by davidbiancolin** [comment]
Amazon has been gracious in awarding us credit grants. That said, $1000 / mo is a little steep -- FireSim tries its best to only keep FPGA instances up when you need them, which should save considerable cost. The boards used in EC2 are not cheap (~ the are roughly equivalent to a alveo U250).

We're working on bringing up local board support. I don't know when it will be ready, but we'll make lots of noise when it is.
