### ISSUE TITLE
Remove copied VerilogMemDelays from tree

### ISSUE THREAD

**Issue by albert-magyar** [firesim/firesim#655]
The fix from freechipsproject/firrtl#1908 was pretty important for FireSim, so it got copied into the tree in #639.

This issue is to remind me to delete it when FIRRTL is bumped far enough to include the upstream fix.

**Comment by davidbiancolin** [comment]
I think we're on track to have a 1.4 bump before the release. So i'm putting the 1.11 milestone on this.

**Comment by timsnyder-siv** [comment]
Does this need to be done as a part of the Bump to FIRRTL 1.4 (#668) or will FAME-5 still work with the locally copied VerilogMemDelays?

**Comment by davidbiancolin** [comment]
It needn't be done as part of the ongoing bump. We're going to try to get that in soon now that CI is passing.

**Comment by timsnyder-siv** [comment]
Makes sense.  However, it looks like the addition of VerilogMemDelays is a conflict that has to be resolved for #668 to merge see https://github.com/firesim/firesim/pull/668/conflicts

**Comment by davidbiancolin** [comment]
Resolved by #668.
