### ISSUE TITLE
Docs Missing init-submodules.sh Step

### ISSUE THREAD

**Issue by hngenc** [firesim/firesim#659]
https://docs.fires.im/en/latest/Running-Simulations-Tutorial/Running-a-Single-Node-Simulation.html#building-target-software

These instructions need to be changed to:

```
cd firesim/sw/firesim-software
./init-submodules.sh
./marshal -v build br-base.json
```

Otherwise, we get this error:
```
Marshal submodule "/home/centos/firesim/target-design/chipyard/software/firemarshal/wlutil/br/buildroot" not initialized. Please run "./init-submodules.sh."
```

**Comment by davidbiancolin** [comment]
If you could PR this, that would be lovely.

**Comment by hngenc** [comment]
I've created one with a very lucky number: https://github.com/firesim/firesim/pull/666

**Comment by davidbiancolin** [comment]
Great, thanks @hngenc.
