### ISSUE TITLE
VerilogAccumulator.scala reset fix.

### ISSUE THREAD

**Issue by linuxbest** [firesim/firesim#685]
https://github.com/firesim/firesim/blob/eb7d1af4964814270b176d4e682fc999e8db561a/sim/src/main/scala/midasexamples/VerilogAccumulator.scala#L52

chisel3.internal.ChiselException: Connection between sink (Bool(IO reset in VerilogAccumulatorImpl)) and source (Reset(IO in unelaborated VerilogAccumulatorDUT)) failed @: Sink (Bool(IO reset in VerilogAccumulatorImpl)) and Source (Reset(IO in unelaborated VerilogAccumulatorDUT)) have different types.

```java
index 0f5ae6e..e1d570a 100644
--- a/sim/src/main/scala/midasexamples/VerilogAccumulator.scala
+++ b/sim/src/main/scala/midasexamples/VerilogAccumulator.scala
@@ -49,7 +49,7 @@ class VerilogAccumulatorDUT extends Module {
   val io = IO(new AccumulatorIO)
   val impl = Module(new VerilogAccumulatorImpl)
   impl.io.clock := clock
-  impl.io.reset := reset
+  impl.io.reset := reset.asBool
   impl.io.in := io.in
   io.out := impl.io.out
 }

**Comment by davidbiancolin** [comment]
Can you open a PR for this?
