### ISSUE TITLE
Can FireSim simulate Rocketchip with bare-metal workloads (without Linux ) ?

### ISSUE THREAD

**Issue by meton-robean** [firesim/firesim#696]
Can FireSim simulate Rocketchip with bare-metal workloads (without Linux ) ?

**Comment by davidbiancolin** [comment]
Yup. There are some baremetal workloads checked in (in deploy/workloads), and i think it's covered in both the FireSim and also FireMarshal docs.

**Comment by meton-robean** [comment]
> Yup. There are some baremetal workloads checked in (in deploy/workloads), and i think it's covered in both the FireSim and also FireMarshal docs.

@davidbiancolin  Thanks a lot! and Is that mean I can  run bare-metal example code on Rocket using FPGA-sim on F1 instance?

**Comment by davidbiancolin** [comment]
That's right. :)
