### ISSUE TITLE
Fix how sourceme scripts deal with ssh-agent when user is using ssh forwarding

### ISSUE THREAD

**Issue by sagark** [firesim/firesim#70]

**Comment by a0u** [comment]
A potential workaround is to ignore agent forwarding and initialize `ssh-agent` locally if the manager is running inside a tmux or screen session, i.e., `$TMUX` or `$STY` is set in the environment.  That at least preserves the convenience of forwarding in the regular case when there is no danger of the session being detached.

**Comment by a0u** [comment]
Fixed by PR #128.
