### ISSUE TITLE
TracerVBridge issue with HeteroConfig

### ISSUE THREAD

**Issue by SeahK** [firesim/firesim#729]
When I tried to build a FPGA image with HeteroConfig, I faced TracerV issue that "ports of extmodule TracerVBridge with defname TracerVBridge are different for an extmodule with the same defname"
For now, I commented out TracerVBridge at BridgeBinder.scala, and it was built. (Though it wouldn't have autocounter features)
![image](https://user-images.githubusercontent.com/54855793/109343888-d99b8000-7822-11eb-95de-a4c16daaa828.png)

**Comment by davidbiancolin** [comment]
Hey Seah can you provide the tuple to reproduce this.

**Comment by SeahK** [comment]
Sorry for late response. The build config is this:

[firesim-rocket-heterocore30-16x16_2048-gemmini]
DESIGN=FireSim
TARGET_CONFIG=DDR3FRFCFS_FireSimGemminiRocketHeteroConfig
PLATFORM_CONFIG=MCRams_F30MHz_BaseF1Config
instancetype=z1d.2xlarge
deploytriplet=None

For the target config, I included
  new WithDefaultFireSimBridges ++
  new WithDefaultMemModel ++
  new WithFireSimConfigTweaks ++
  new chipyard.LargeBoomAndGemminiRocketConfig

and that boom and gemmini rocket config is core 0 to Boom and 1,2,3,4 to Rocket+Gemmini

Thanks!
