### ISSUE TITLE
Get (RTL) power estimation in FireSim

### ISSUE THREAD

**Issue by sabbaghm** [firesim/firesim#733]
The vectorless (probabilistic) power estimation out of Xilinx tools is not really reflective of the actual power profile. 
* Is it possible to get more accurate power estimation for our designs in FireSim? (perhaps using self-generate switching activity files) 
* Is there any dedicated tool and documentation for that?

Thank you!

**Comment by davidbiancolin** [comment]
We don't currently have a flow for that. But there is interest in bringing up Donggyu Kim's Simmani work in the future. Stay tuned to our google groups for info on that.
