### ISSUE TITLE
Localization of FireSim

### ISSUE THREAD

**Issue by SihaoLiu** [firesim/firesim#744]
I would like to use FireSim on the U280 of my local machine. But it seems that FireSim can only be used on AWS F1. I checked the paper and it said that FireSim will support local FPGA in the near future.
Is there any ongoing progress of FireSim localization?

**Comment by davidbiancolin** [comment]
Hey SihaoLiu, 

We _are_ working on the U250s. Stay tuned to our google groups for announcements. 

- David
