### ISSUE TITLE
The operation result of the workload on the F1 instance is not copied to the management instance

### ISSUE THREAD

**Issue by hz1490919302** [firesim/firesim#745]
I have run a management instance on Firesim, which is used to start the F1 instance, I set out Outputs in the .json file. I use _Firesim Launchrunfarm \ INFRASETUP \ RunworkLoad_ to launch the F1 instance, then use _SSH 192.168.xx_ to enter the F1 instance, use _Screen -R fsim0_ to enter the simulated RISCV environment, when the running workload is over, I run _Poweroff,_ but work The loaded output file is not copied to my management instance. It shows
**Umount: Can't Remount / dev / iceblk read-only
Umount: None busy - Remounted Read-Only.**
 Can you tell me what to do?
![image](https://user-images.githubusercontent.com/27117133/113483421-27298f00-9458-11eb-8cf9-8bb2a532a55a.png)

**Comment by davidbiancolin** [comment]
can you provide more context around the umount?
