### ISSUE TITLE
Can FireSim support ubuntu image (64bit) for rocket core?

### ISSUE THREAD

**Issue by heojun18** [firesim/firesim#756]
When I went through the tutorial, I found out that FireSim currently supports fedora image (32bit).
I want to run ubuntu image (64bit) to run more complex workloads.
Does FireSim support ubuntu image (64bit) ?
If this is not possible, can fedora images (64 bit) be supported?

**Comment by davidbiancolin** [comment]
Fedora images are supported, and FireMarshal (in Chipyard) handles much of the automation of building those images.

**Comment by davidbiancolin** [comment]
See: https://docs.fires.im/en/latest/Advanced-Usage/Workloads/Booting-Fedora.html
