### ISSUE TITLE
Run a RV32 core?

### ISSUE THREAD

**Issue by alexthomas1** [firesim/firesim#757]
I am new to Firesim and I have been trying to simulate an RV32GC core, but I am unable to wrap my head around this. It doesn't seem the option of RV32/RV64 exists based on the configurations. Any tips on getting an RV32 core?

**Comment by davidbiancolin** [comment]
This is more of a chipyard-specific question (which you can ask here, https://groups.google.com/g/chipyard). FireSim itself doesn't make any assumptions about the ISA of the core.  Once you've built a 32-bit configuration, you just need to make sure your boot binaries and file system images are compatible.
