### ISSUE TITLE
 print out the print statement or enable the assert statement

### ISSUE THREAD

**Issue by hz1490919302** [firesim/firesim#783]
Excuse me，how to make the FireSimLargeBoomConfig running on the EC2 F1 instance print out the print statement in the boom or enable the assert statement when running the binary file?

**Comment by davidbiancolin** [comment]
Hey @hz1490919302, these questions are best posted to our mailing list: https://groups.google.com/g/firesim

I'd start here:
https://docs.fires.im/en/latest/Advanced-Usage/Debugging-and-Profiling-on-FPGA/Assertion-Synthesis.html

and here:
https://docs.fires.im/en/latest/Advanced-Usage/Debugging-and-Profiling-on-FPGA/Printf-Synthesis.html
