### ISSUE TITLE
CI Theory: Issues running FPGA tests on multiple PRs at the same time

### ISSUE THREAD

**Issue by abejgonzalez** [firesim/firesim#926]
I think there is an issue with running FPGA's tests at the same time on different PRs due to sharing the same runfarm tag in the `.ini` files. Probably should double-check this or have runfarm tags be unique to PR run.

Related failures: 
https://github.com/firesim/firesim/runs/5114215678?check_suite_focus=true
https://github.com/firesim/firesim/runs/5114315114?check_suite_focus=true

**Comment by davidbiancolin** [comment]
That's almost definitely the problem. Using the workflow ID or w.e in the tag makes sense.
