### ISSUE TITLE
Error Running Workload on Fresh Release 1.13

### ISSUE THREAD

**Issue by CobbledSteel** [firesim/firesim#949]
Building a single-node no-nic config on 1.13 results in the following error printed in the uartlog:

Unable to get AFI information from slot. Are you running as root
INVALID RETCODE: 24
Failure while detaching from the fpga: -22

Patch that fixes the issue:

diff --git a/sim/midas/src/main/cc/simif_f1.cc b/sim/midas/src/main/cc/simif_f1.cc
index 040a2093..ca149972 100644
--- a/sim/midas/src/main/cc/simif_f1.cc
+++ b/sim/midas/src/main/cc/simif_f1.cc
@@ -64,8 +64,8 @@ void simif_f1_t::fpga_setup(int slot_id) {
     uint16_t pci_vendor_id = 0x1D0F; /* Amazon PCI Vendor ID */
     uint16_t pci_device_id = 0xF000; /* PCI Device ID preassigned by Amazon for F1 applications */
 
-    int rc = fpga_pci_init();
-    check_rc(rc, "fpga_pci_init FAILED");
+    int rc = fpga_mgmt_init();
+    check_rc(rc, "fpga_mgmt_init FAILED");

**Comment by abejgonzalez** [comment]
I had to fix this in the local FPGA work in https://github.com/firesim/firesim/blob/72b51474eab6e3632d2f273d5d850302aa6c9f22/sim/midas/src/main/cc/simif_f1.cc#L67-L68. Does anyone see the same error on their end? If so we can re-cut a minor release?
