### ISSUE TITLE
fasedtests/Makefrag has syntax errors

### ISSUE THREAD

**Issue by timsnyder-siv** [firesim/firesim#994]
https://github.com/firesim/firesim/blob/e33e9aeaaa78bff0c430f44a742a78b8297d336a/sim/src/main/makefrag/fasedtests/Makefrag#L32-L35

Has two syntax errors.  I'm not sure how this hasn't been causing failing tests in CI.  The first one is using `{}` around `${firesim_base_dir}` unless somehow SBT figures out the right thing there.

The second one is definitely causing the chipyard chisel files to not be in the dependency list and causes make errors but I suppose everything would build fine.  @davidbiancolin do you think the first one is getting figured out by SBT?

**Comment by timsnyder-siv** [comment]
I guess make handles the `{}` in the variable dereference.

**Comment by davidbiancolin** [comment]
the first one is valid SBT syntax, the second _should_ be handled by Make.

Are you trying to run this from a Chipyard-as-top?

**Comment by timsnyder-siv** [comment]
No.  firesim as top.

Since the first is valid SBT syntax, then I guess make is smart enough to not try to use `${` as a variable.  I still would have expected that you'd need to have `firesim_sbt_project := {file:$${firesim_base_dir}/}firesim`

I should have been more clear about where the second one is.  On line 35, `(chipyard_dir)` needs to have a `$` in front of it.  Like I said, this is only an issue with Make not having the deps correct and seeing changes to scala files needing to rebuild the appropriate target but I'll still fix it in my conda branch.

**Comment by davidbiancolin** [comment]
> Since the first is valid SBT syntax, then I guess make is smart enough to not try to use `${` as a variable. I still would have expected that you'd need to have `firesim_sbt_project := {file:$${firesim_base_dir}/}firesim`

Ok, so i was confused. Make needs to substitute ${firesim_base_dir} for this work. It needs to be an absolute path to the directory for the project URI to resolve. 

> I should have been more clear about where the second one is. On line 35, `(chipyard_dir)` needs to have a `$` in front of it. Like I said, this is only an issue with Make not having the deps correct and seeing changes to scala files needing to rebuild the appropriate target but I'll still fix it in my conda branch.

This one is definitely busted. Please do fix at your leisure.

**Comment by timsnyder-siv** [comment]
For the first one, I always forget that there is no difference in Makefiles between using `{}` around variables and `()`.  I just never use braces.

I'll fix the second one.

**Comment by timsnyder-siv** [comment]
I fixed the error on line 35 in #986
